import { CardItemData } from "../components/Card";

export const cardItemData: CardItemData[] = [
  {
    link: "https://www.bogleheads.org/wiki/Household_budgeting",
    imgSrc: "https://www.bogleheads.org/w/images/BogleheadsSiteLogo.svg",
    title: "Household budgeting",
    text: "Individuals establish a household budget in an effort to understand their cash flow- how much they make and how much they spend. A budget is a tool that can help individuals plan for desired purchases and establish savings for reaching financial goals.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "goal setting",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "cash flow management",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.nerdwallet.com/article/finance/how-to-budget",
    imgSrc:
      "https://www.nerdwallet.com/assets/blog/wp-content/uploads/2016/10/GettyImages-1327807534-2400x1440.jpg",
    title: "Budgeting 101: How to Budget Money",
    text: "Follow this guide to learn how to budget money. Create a budget using the 50/30/20 rule to split your income between needs, wants, savings and debt repayment.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "budgeting tools",
      "goal setting",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "cash flow management",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://n26.com/en-eu/blog/budgeting-tips",
    imgSrc:
      "https://images.ctfassets.net/q33z48p65a6w/6DL2li0mx2cMX1p4G8tLaE/cfa1fb8f6586fdae68a33577c4a21323/budgeting-tips-How-to-save-money-N26.jpeg?fit=thumb&fm=webp&h=1075&q=70&w=1920",
    title: "5 smart budgeting tips for first-time savers",
    text: "Working out how to budget your money doesn’t need to be hard. These personal budgeting tips are all you need to know to start saving money today.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "goal setting",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.getrichslowly.org/how-to-budget/",
    imgSrc:
      "https://www.getrichslowly.org/wp-content/uploads/how-to-budget-guide.jpg",
    title: "How to budget: A pain-free guide to building a budget that works",
    text: "To get out of debt and save money, it helps to know how to budget. Many people think budgeting is painful. It doesn't have to be. Here are some tips.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.investopedia.com/articles/pf/10/8-tips-organize-finances.asp",
    imgSrc:
      "https://www.investopedia.com/thmb/Rp11TpCqvluZibMO4cndE9NFZ5Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/156416606-5bfc2b8b46e0fb00517bdff7.jpg",
    title: "8 Steps To An Organized Financial Life",
    text: "Disorganization makes planning difficult, and that can cost you big-time. Follow these eight steps to an organized financial life.",
    categories: [
      "money management",
      "financial planning",
      "budgeting",
      "saving",
      "expenses",
      "income",
      "cash flow management",
      "financial organization",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "tax planning",
      "estate planning",
      "record-keeping",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.investopedia.com/personal-finance/how-to-build-emergency-fund/",
    imgSrc:
      "https://www.investopedia.com/thmb/wDvwg71si21r1tyOTYmlF40v6o8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/thinkstockphotos-200171422-001-5bfc2b4b46e0fb0026015ff2.jpg",
    title: "How to Build an Emergency Fund",
    text: "Here are some tips for putting aside money for a rainy day—or, to be precise, three to six months’ worth of them. Learn how to grow an emergency fund.",
    categories: [
      "money management",
      "financial planning",
      "emergency fund",
      "saving",
      "cash reserves",
      "financial security",
      "budgeting",
      "debt management",
      "income",
      "expenses",
      "financial goals",
      "risk management",
      "investing",
      "interest rates",
      "high-yield savings accounts",
      "emergency fund",
      "emergency expenses",
      "insurance",
      "retirement planning",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.investopedia.com/articles/personal-finance/100516/setting-financial-goals/",
    imgSrc:
      "https://www.investopedia.com/thmb/UgFhPGJ-admf4boc9UZtHermrRY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1306844428-7898510289944252a593f9ed446c2251.jpg",
    title: "How to Set Financial Goals for Your Future",
    text: "To live comfortably now and in retirement, setting financial goals for the short-, mid-, and long-term is crucial. Here are the key steps to take.",
    categories: [
      "money management",
      "financial planning",
      "financial goals",
      "budgeting",
      "saving",
      "investing",
      "debt management",
      "retirement planning",
      "emergency fund",
      "wealth building",
      "goal setting",
      "motivation",
      "lifestyle goals",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.clevergirlfinance.com/blog/the-purpose-of-budgets/",
    imgSrc:
      "https://www.clevergirlfinance.com/wp-content/uploads/2023/01/The-purpose-of-budgets.jpg",
    title: "The Purpose Of Budgets: 11 Critical Reasons Why You Need One!",
    text: "The purpose of budgets isn&#039;t to rein you in. Instead, this tool can help you reach your financial goals. Find out why budgeting matters.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "cash flow management",
      "mindset",
      "discipline",
      "prioritization",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://hbr.org/2021/08/why-are-we-so-emotional-about-money",
    imgSrc:
      "https://hbr.org/resources/images/article_assets/2021/08/A_Aug21_13_Title_Ramit-Sethi.jpg",
    title: "Why Are We So Emotional about Money?",
    text: "If money brings up a lot of emotions for you, you’re not alone. Financial expert Ramit Sethi explains our relationship with money is just as personal and valuable as any other relationship in our life. Here are some ways to build a healthier relationship with money. First, know that it’s okay to feel emotional about money. Use them to understand your values, your fears, your needs, and your wants. Then, start educating yourself about money. Understand what terms like credit, loan, compound interest, etc. mean. Often, the fear of money comes from a lack of knowledge or awareness about it. Finally, be inspired by money. Instead of focusing on what you don’t have, think about what money can buy. Don’t just focus on the materialistic aspects but also the experiences it affords you.",
    categories: [
      "money management",
      "financial psychology",
      "behavioral finance",
      "emotions",
      "mindset",
      "decision-making",
      "budgeting",
      "saving",
      "investing",
      "debt management",
      "financial planning",
      "financial stress",
      "anxiety",
      "happiness",
      "self-worth",
      "social comparison",
      "mental health",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.inverse.com/mind-body/how-to-achieve-financial-success-the-healthy-way",
    imgSrc:
      "https://imgix.bustle.com/uploads/image/2020/7/28/934b2dcc-6d73-49bd-8f53-98cb38309c73-gettyimages-912018754.jpg?w=1200&amp;h=630&amp;fit=crop&amp;crop=faces&amp;fm=jpg",
    title: "Financial goals can make you feel good — if you follow 3 key rules",
    text: "A psychologist explains how to maintain heath and well-being while pursuing financial goals.",
    categories: [
      "health",
      "wellness",
      "mindfulness",
      "habits",
      "success",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "time management",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.vox.com/even-better/23591325/money-debt-emotions-financial-therapist",
    imgSrc:
      "https://cdn.vox-cdn.com/thumbor/dPucASivDUqeKv-GYFYC4igJXuA=/0x0:8333x4363/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/24420862/GettyImages_1368395193.jpg",
    title: "You’re not bad with money. But you can get better.",
    text: "A financial therapist explains how to shift your personal money narratives.",
    categories: [
      "debt",
      "emotions",
      "mental health",
      "therapy",
      "counseling",
      "psychology",
      "behavioral economics",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "anxiety",
      "stress",
      "trauma",
      "mindfulness",
      "self-care",
    ],
    length: 0,
    points: 0,
  },
  {
    link: "https://www.cnbc.com/2021/06/28/here-are-5-ways-to-spend-money-that-can-actually-make-you-happier.html",
    imgSrc:
      "https://image.cnbcfm.com/api/v1/image/106902767-1624632987835-gettyimages-599774043-19c2e5b2-45e4-4731-8b30-27bf66fa2a3b.jpeg?v=1624633088&amp;w=1920&amp;h=1080",
    title: "Here are 5 ways to spend money that can actually make you happier",
    text: "You may be ready to spend more money, but will it bring you joy? Researcher Elizabeth Dunn details five happy spending strategies.",
    categories: [
      "happiness",
      "spending",
      "psychology",
      "well-being",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "philanthropy",
      "health",
      "wellness",
      "education",
    ],
    length: 0,
    points: 0,
  },
];
