import { CardItemData } from "../components/Card";

export const cardItemData: CardItemData[] = [
  {
    link: "https://www.bogleheads.org/wiki/Household_budgeting",
    imgSrc: "https://www.bogleheads.org/w/images/BogleheadsSiteLogo.svg",
    title: "Household budgeting",
    text: "Individuals establish a household budget in an effort to understand their cash flow- how much they make and how much they spend. A budget is a tool that can help individuals plan for desired purchases and establish savings for reaching financial goals.",
    categories: [
      "budgeting",
      "retirement planning",
      "savings",
      "debt reduction",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question: "Why do individuals establish a household budget?",
        correctAnswer: "All of the above",
        incorrectAnswers: [
          "To track their cash flows",
          "To plan for desired purchases and establish savings",
          "To keep spending under control",
        ],
      },
      {
        question:
          "What is the difference between a descriptive and prescriptive budget?",
        correctAnswer:
          "Descriptive budgets simply track cash flows while prescriptive budgets plan for future spending",
        incorrectAnswers: [
          "Descriptive budgets plan for future spending while prescriptive budgets simply track cash flows",
          "Descriptive budgets control income and spending while prescriptive budgets do not",
          "Descriptive budgets do not track income and expenses while prescriptive budgets do",
        ],
      },
      {
        question: "What are some ways to control flexible expenses?",
        correctAnswer: "Prioritize needs over wants",
        incorrectAnswers: [
          "Cut expenses to the bare minimum",
          "Increase spending to improve quality of life",
          "None of the above",
        ],
      },
      {
        question: "The Bogleheads recommend paying yourself first.",
        correctAnswer: "first",
      },
    ],
    testedContent:
      "Individuals establish a household budget in an effort to understand their cash flow- how much they make and how much they spend. A budget is a tool that can help individuals plan for desired purchases and establish savings for reaching financial goals. Budgets are often essential for people who desire to keep spending under control. For individuals approaching retirement tracking income and expenses can help determine the needed income required for retirement planning.\nA budget can be descriptive, in that it simply tracks a household's cash flows[note 1] or prescriptive, in which a plan of future spending is budgeted, and income and spending is controlled in an attempt to track the proposed budget.\nPerhaps the most important idea underlying the Bogleheads approach to investing is recognizing you need to save a significant portion of income every month to have enough money for a comfortable retirement. There is no substitute for spending less than you earn.\nThe Bogleheads approach to developing a workable financial plan is to have a sensible household budget - one that provides for needed expenditures, discretionary pleasures, savings for big ticket items, and savings for long term retirement planning. Avoid excess debt, such as credit cards and home equity loans. If you have such debt, pay off those balances first. Reduce expenses and unneeded debt so you can consistently set aside a portion of earnings for decades. If you don't save enough, no amount of financial trickery will provide the returns needed for a comfortable retirement.\nBudget worksheets are available from many sources; choose a format that you are comfortable with. The example below illustrates the process.\nRecord your income in the left column. As you can see from the example below, there are spaces on your worksheet for other incomes sources that might fit your personal situation. As you record your income, be sure to consider whether income sources are continuous or whether they might stop in the near future. For example, if your receive unemployment benefits, keep in mind when you will stop receiving these benefits.\nYou also might want to make adjustments for income you receive on a yearly or quarterly basis, such as tax refunds or bonus checks.\nCalculate your total income by adding the numbers in the left column. This number represents the amount of income you receive in a month.\nNext, list your monthly expenses in the right-hand column.\nBegin by listing your fixed expenses. Fixed expenses are items you have little or no control over. You will pay a fixed amount for these expenses each month.\nThe next group is flexible expenses, which are expenses that you can control. When thinking about flexible expenses, think about what you need and what you want. This will help you to control your spending in this category. What are some ways that you could control the costs of these expenses?\nAlso, make sure to pay yourself first. Set aside money from each paycheck and put it towards your savings. You will notice in the example below that “savings” is listed as an expense.\nCalculate your total expenses by adding the numbers in the right column. This number represents the amount of expenses you spend in a month.\nNow, compare your Total Income (left column) against Total Expenses (right column). If your income is more than your expenses, you are spending less than you earn and are on the right path to live below your means.\nOtherwise, you should replan your budget and reconsider whether or not you are ready to invest.",
  },
  {
    link: "https://www.nerdwallet.com/article/finance/how-to-budget",
    imgSrc:
      "https://www.nerdwallet.com/assets/blog/wp-content/uploads/2016/10/GettyImages-1327807534-2400x1440.jpg",
    title: "Budgeting 101: How to Budget Money",
    text: "Follow this guide to learn how to budget money. Create a budget using the 50/30/20 rule to split your income between needs, wants, savings and debt repayment.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "budgeting tools",
      "goal setting",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "cash flow management",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://n26.com/en-eu/blog/budgeting-tips",
    imgSrc:
      "https://images.ctfassets.net/q33z48p65a6w/6DL2li0mx2cMX1p4G8tLaE/cfa1fb8f6586fdae68a33577c4a21323/budgeting-tips-How-to-save-money-N26.jpeg?fit=thumb&fm=webp&h=1075&q=70&w=1920",
    title: "5 smart budgeting tips for first-time savers",
    text: "Working out how to budget your money doesn’t need to be hard. These personal budgeting tips are all you need to know to start saving money today.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "goal setting",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.getrichslowly.org/how-to-budget",
    imgSrc:
      "https://www.getrichslowly.org/wp-content/uploads/how-to-budget-guide.jpg",
    title: "How to budget: A pain-free guide to building a budget that works",
    text: "To get out of debt and save money, it helps to know how to budget. Many people think budgeting is painful. It doesn't have to be. Here are some tips.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.investopedia.com/articles/pf/10/8-tips-organize-finances.asp",
    imgSrc:
      "https://www.investopedia.com/thmb/Rp11TpCqvluZibMO4cndE9NFZ5Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/156416606-5bfc2b8b46e0fb00517bdff7.jpg",
    title: "8 Steps To An Organized Financial Life",
    text: "Disorganization makes planning difficult, and that can cost you big-time. Follow these eight steps to an organized financial life.",
    categories: [
      "money management",
      "financial planning",
      "budgeting",
      "saving",
      "expenses",
      "income",
      "cash flow management",
      "financial organization",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "tax planning",
      "estate planning",
      "record-keeping",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.investopedia.com/personal-finance/how-to-build-emergency-fund",
    imgSrc:
      "https://www.investopedia.com/thmb/wDvwg71si21r1tyOTYmlF40v6o8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/thinkstockphotos-200171422-001-5bfc2b4b46e0fb0026015ff2.jpg",
    title: "How to Build an Emergency Fund",
    text: "Here are some tips for putting aside money for a rainy day—or, to be precise, three to six months’ worth of them. Learn how to grow an emergency fund.",
    categories: [
      "emergency fund",
      "saving",
      "debt",
      "household expenses",
      "financial plan",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question: "How much should you keep in your emergency fund?",
        correctAnswer: "Three to six months of expenses",
        incorrectAnswers: ["One month of expenses", "Two months of expenses"],
      },
      {
        question:
          "How can you achieve your three-month target for your emergency fund?",
        correctAnswer: "By downgrading your cell phone service",
        incorrectAnswers: [
          "By buying a more expensive car",
          "By going on a two-week vacation",
        ],
      },
      {
        question:
          "How much money will you have at the end of the year if you dedicate $5 per day to your emergency fund?",
        correctAnswer: "$1,825",
        incorrectAnswers: ["$500", "$3,650"],
      },
      {
        question:
          "Three months' worth of expenses is not a lot compared to what you'll need over the course of 20 or 30 years in retirement.",
        correctAnswer: "Three",
      },
    ],
    testedContent:
      "Having an emergency fund is a necessity. Think of it as a shock absorber for the bumps of life, one that’ll keep you from adding to the load of debt you most likely already carry. The coronavirus outbreak has shone a giant spotlight on the difference having an emergency fund makes when a crisis hits.\nRead on for details on how to build an emergency fund and just how much you’ll need to save for it.\nKEY TAKEAWAYS\nAn emergency fund is a key component of any good financial plan.\nThe rule of thumb is that you need to keep between three and six months’ worth of household expenses in your emergency fund.\nIn order to populate your fund, you should find ways to economize and contribute those savings—along with any financial windfalls—to it.\nWhile some call having one to two months’ wages in reserve ideal, most financial experts say that the recommended emergency fund amount should cover three to six months’ worth of household expenses. That’s a great idea, and a key part of any sound financial plan, but it also requires some effort to achieve.\nThe first step in the process is to figure out how much you spend each month. Consumer expenditure figures released in April 2019 by the U.S. Bureau of Labor Statistics indicate that the average annual expenditure per consumer unit, which is similar to a household, was $60,060 in 2017 (the most recent year for which data is available). This data is broken down by month in the table below. The months in bold highlight the cumulative quarterly expenses, and therefore, the recommended cash reserve for the average household.\nWhile your household expenses may be higher or lower than the average, there’s no doubt that even three months’ worth of expenses is a big number. One look at that number and the average person’s first reaction is, “I can’t come up with that kind of money.”\nThe amount of money required to populate a proper emergency fund is certainly significant, but we live in uncertain times with uncertain economies, especially in the wake of the coronavirus. Corporate loyalty is a thing of the past, and unemployment can happen unexpectedly, usually at the worst possible moment. Even without a global crisis, emergencies such as sudden illness or disability, major car repairs or a new roof, can be expensive, and there’s never a good time for these things to happen.\nWhile it’s probably true that you don’t have an extra $15,015 lying around, everything is relative. Even six months’ worth of expenses is a puny number compared to the amount you will need to save for retirement, and there’s not a savvy investor out there who balks at the idea of stashing away so much money that they will never need to work again. When compared to what you’ll need over the course of 20 or 30 years in retirement, three months’ worth of expenses doesn’t look like much.\nThough the amount of money needed in your fund may seem daunting at first, remember that it is a drop in the bucket compared with the amount you will have to save for retirement.\nWith that perspective in mind, let’s consider how to save for an emergency fund. Approach this effort the same way you would approach any other financial goal. Put together a plan and execute it. The first step is to determine how much you spend each month. Housing, transportation, and food will likely be the categories that eat up most of your cash. The average household spends 62% of its income, which averages $73,573 before taxes, on these items, according to the BLS Consumer Expenditures report.\nOnce you know your total expenses for each month, multiply that number by three. Reaching that number will be your initial goal. To achieve your three-month target, you need to start saving money.\nIf we assume your initial goal is $10,000, the table below illustrates how much you will need to save each month, over a five-year or two-and-a-half-year period.\nBuying a less expensive car the next time you are shopping for an auto and downgrading your cell phone service are two easy ways to come up with some cash to fund your savings plan. Skipping that two-week vacation, cutting down on the amount you spend dining out, and saving your next raise or bonus are also achievable methods of adding to your emergency fund.\nThe key is to add to the fund at regular intervals. Ideally, you should treat it like any other recurring bill you must pay each month. Dedicate the appropriate amount from your paycheck and set it aside. While most people have no qualms about regularly sending enormous amounts of money to credit card companies, they balk at the idea of paying themselves first. Change that equation.\nIf you are among the many investors who don’t have a rainy day fund stashed away in case of emergencies, there’s no time like the present to start saving. Even if you don’t have the fortitude to address the project with a dedicated savings program, you can start simple: Take the change out of your pockets at the end of the day and put it in a jar. Look into micro-investing platforms, such as Acorns, that round up purchases made from linked accounts and collect and invest the change.\nYou could also eat at home instead of dining out and “tip” yourself by adding a few bucks to your emergency fund. If you get cash back on your credit cards or just paid off a big debt, such as a personal loan or an automobile, put that newfound money into your fund. If you get a tax refund, deposit the check into your fund. If you manage to dedicate just $5 per day to your effort, you’ll have $1,825 at the end of the year; that’s $9,125 in just five years.\nMoney market funds and high-interest savings accounts are two good places to park your emergency fund. You need safe, liquid options so that your money is accessible in times of need. These choices make it harder for you to dip into it (face it: you’ll be tempted to from time to time), and you’ll also earn a bit of return on the money.\nView your emergency fund like an insurance policy. Once you have it, guard it carefully. It’s not a piggy bank. You should not using it for incidental expenses. In fact, as your salary rises, be sure to up the amount to match your new situation.\nUse the fund only in the event of an emergency and spend it carefully when you do need to draw on it. Remember, once that money is spent, it always takes much longer than anticipated to replace it. Start now and save whatever you can, even if it isn’t much. Having an emergency fund gives you a better shot at weathering a crisis without running up a credit card balance or taking out a personal loan.\nFinding the right financial advisor that fits your needs doesn’t have to be hard. SmartAsset’s free tool matches you with fiduciary financial advisors in your area in 5 minutes. Each advisor has been vetted by SmartAsset and is legally bound to act in your best interests. If you’re ready to be matched with local advisors that will help you achieve your financial goals, get started now.",
  },
  {
    link: "https://www.investopedia.com/articles/personal-finance/100516/setting-financial-goals",
    imgSrc:
      "https://www.investopedia.com/thmb/UgFhPGJ-admf4boc9UZtHermrRY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1306844428-7898510289944252a593f9ed446c2251.jpg",
    title: "How to Set Financial Goals for Your Future",
    text: "To live comfortably now and in retirement, setting financial goals for the short-, mid-, and long-term is crucial. Here are the key steps to take.",
    categories: [
      "money management",
      "financial planning",
      "financial goals",
      "budgeting",
      "saving",
      "investing",
      "debt management",
      "retirement planning",
      "emergency fund",
      "wealth building",
      "goal setting",
      "motivation",
      "lifestyle goals",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.clevergirlfinance.com/blog/the-purpose-of-budgets",
    imgSrc:
      "https://www.clevergirlfinance.com/wp-content/uploads/2023/01/The-purpose-of-budgets.jpg",
    title: "The Purpose Of Budgets: 11 Critical Reasons Why You Need One!",
    text: "The purpose of budgets isn't to rein you in. Instead, this tool can help you reach your financial goals. Find out why budgeting matters.",
    categories: [
      "budgeting",
      "money management",
      "financial planning",
      "saving",
      "expenses",
      "income",
      "financial goals",
      "debt management",
      "credit cards",
      "emergency fund",
      "retirement planning",
      "investing",
      "cash flow management",
      "mindset",
      "discipline",
      "prioritization",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://hbr.org/2021/08/why-are-we-so-emotional-about-money",
    imgSrc:
      "https://hbr.org/resources/images/article_assets/2021/08/A_Aug21_13_Title_Ramit-Sethi.jpg",
    title: "Why Are We So Emotional about Money?",
    text: "If money brings up a lot of emotions for you, you’re not alone. Financial expert Ramit Sethi explains our relationship with money is just as personal and valuable as any other relationship in our life. Here are some ways to build a healthier relationship with money. First, know that it’s okay to feel emotional about money. Use them to understand your values, your fears, your needs, and your wants. Then, start educating yourself about money. Understand what terms like credit, loan, compound interest, etc. mean. Often, the fear of money comes from a lack of knowledge or awareness about it. Finally, be inspired by money. Instead of focusing on what you don’t have, think about what money can buy. Don’t just focus on the materialistic aspects but also the experiences it affords you.",
    categories: [
      "money management",
      "emotional intelligence",
      "financial literacy",
      "financial psychology",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question: "What is the author's relationship with money?",
        correctAnswer:
          "The author feels guilty when spending money on themselves.",
        incorrectAnswers: [
          "The author is indifferent to money.",
          "The author is always comparing their financial situation to that of their friends.",
        ],
      },
      {
        question:
          "What makes money decisions complicated, according to Ramit Sethi?",
        correctAnswer: "The fact that emotions are always involved.",
        incorrectAnswers: [
          "The lack of mathematically correct answers.",
          "The need to consult with a financial advisor.",
        ],
      },
      {
        question:
          "What is the cycle of negative emotion that the author is trying to get out of?",
        correctAnswer: "The cycle of negative self-talk.",
        incorrectAnswers: [
          "The cycle of comparing oneself to others.",
          "The cycle of feeling guilty about having a student loan.",
        ],
      },
      {
        question:
          "Ramit Sethi say that the psychology behind our relationship with money is underrated.",
        correctAnswer: "underrated",
      },
    ],
    testedContent:
      "Why Are We So Emotional about Money?\nIf money brings up a lot of emotions for you, you’re not alone. Financial expert Ramit Sethi explains our relationship with money is just as personal and valuable as any other relationship in our life. Here are some ways to build a healthier relationship with money.\nFirst, know that it’s okay to feel emotional about money. Use them to understand your values, your fears, your needs, and your wants.\nThen, start educating yourself about money. Understand what terms like credit, loan, compound interest, etc. mean. Often, the fear of money comes from a lack of knowledge or awareness about it.\nFinally, be inspired by money. Instead of focusing on what you don’t have, think about what money can buy. Don’t just focus on the materialistic aspects but also the experiences it affords you.\nHow do you feel about money?\nI’ll go first. Money allows me to pay bills and function in a capitalistic world, but besides that, I don’t associate positive emotions with it.\nMoney, I imagine, is something that belongs in my future. I feel greedy every time I spend it on myself and often fall into the trap of comparing my financial situation to that of my friends. I spiral into a dark hole of negative self-talk — the expensive events I can’t afford playing on a loop in my head — because I know I will spend my entire 20s chipping away at my massive student loan debt.\nMoney is messy. It’s complicated. It’s oh-so-very-emotional. I know I’m not the only person who feels this way. So, how do we cope?\nAccording to Ramit Sethi, author of I Will Teach You To Be Rich, the psychology behind our relationship with money is very underrated. In his new podcast, Sethi dives into the confusing emotions many of us feel when it comes to our finances. His advice is clear: Our feelings are almost always unrelated to the financial decisions we make and indicative of something much deeper.\nI spoke with Ramit about what makes money so emotional and how to build healthier relationships with it. Here’s what he had to say.\nWhy is money such an emotional topic? \nAnything important in our lives is emotional. Our relationships are emotional, our work is emotional, and so is our money. One of the misconceptions about money is that it’s all math. We believe that there is a mathematically correct answer for questions like, “Should I buy a house or rent one?” or “Should I go to graduate school?” or “Should I take this job?” or “Should I negotiate a higher salary?”\nSure, doing the math can help you answer these questions, but there’s no foolproof formula to making money decisions.\nBuying a house can mean you don’t have to pay rent. Renting, on the other hand, can help you live in a city you’ve always wanted to live in. Going to university might be your route to a better career or to a promotion. Our relationship with money is just as personal and valuable as any other relationship in our life. So, it’s an emotional topic — as it should be.\nI find that the feelings money elicits in me are mostly negative, and this is true for many of my peers. For example, I have a student loan that I’ve been repaying for the last five years. Even though the loan paid for my college education, I feel a lot of shame and guilt when I think about my debt. Rationally, I know getting the degree was a good decision, but it doesn’t feel good anymore. I feel anxious when I look at what I’m earning versus how much I’m saving and investing. How do I get out of this cycle of negative emotion? \nFirst of all, it’s very normal to feel different emotions at different stages of your life. Imagine that you are going out to climb a mountain. You spend months training for it, you buy your gear and equipment, and you get to the bottom of the mountain. You feel good. That’s how a lot of us feel when we’re starting college and applying for a loan. You may not fully understand how that’s going to impact the rest of your life but you’re ready to go.\nThen, you start climbing the mountain and you reach the first peak. You may look around and say, “Wow, I climbed a long way,” but you also realize there’s a lot further to go than you realized. You might start thinking about everything you need to do to keep going. The end of college can feel the same way. Now, you have a college education, but you also have debt.\nThis is where it gets tricky because a lot of us fixate on all the feelings around how much there’s left to do. In terms of a loan, that looks like thinking about what you’ve mortgaged, the interest on your loan, how much money you have to set aside every month to make a payment, and the kind of job you’d have to do to get where you want to go next.\nOften, this feeling can be aggravated by looking around and comparing yourself to others or even your own life before you took on debt. You can’t go on vacation, but your friends are able to. You feel like you’re missing out. Someone just bought a car, but you’re not able to afford a car right now. Maybe your parents are helping you out to repay your loans, and that makes you feel guilty. Slowly, you may begin to ask yourself if it was worth it.\nDo any of these resonate with you?\nAll of them! You’re right about the journey. Even after five years, it looks like I have a long way to go. Is that normal?\nIt is. But your feelings are not correlated with your debt. You may think that paying off your debt will make you happy, but once you do, there’s going to be another thing to worry about. This doesn’t mean that your feelings aren’t valid. It just means that your emotions don’t always give you the full picture of your financial situation.\nLet’s try this instead: What do you imagine your life would be like if you didn’t have any debt?\nHonestly, debt feels like an obstacle. If I could remove that obstacle, I imagine that I’d be able to make choices more freely.  \nOkay, let’s look at that more closely. When you speak about debt, it sounds like you want to go back to zero and start fresh.\nThis is classic example of a scarcity mindset, where you are focused on what you don’t have, or you believe there will never be enough of something. This could be money, time, or anything really. This scarcity mindset can make you operate from a place of fear. You’re playing not to lose instead of playing to win. You feel like you have to give up on vacations. You might be afraid of negotiating your salary because you’re scared of losing your job — and having a job feels more secure than asking for what you want.\nOften, it’s this feeling that people in your situation need to work on. I know it may be difficult to believe, but this feeling of scarcity or fear doesn’t go away after repaying a debt.\nEven if you were to win $1 million tomorrow, you would find yourself stressing about something else in life, for instance, what to do with that $1 million or if it’s even really “enough” money to live the life you want. Your mindset won’t change unless you specifically work to improve it.\nHere’s what I want you to know: You don’t have to wait another five or 10 years to do what you really want to do today.\nHow does one shift their mindset? It doesn’t sound easy at all. \nYes, it will take time. The simplest way to reframe this kind of thinking is to flip how you think about your financial decisions. Instead of thinking about everything your loan couldn’t do for you, ask yourself what you gained from it.\nPerhaps you gained an opportunity to study abroad or live on your own. Perhaps you met people who you still have relationships with, who taught you things, and or who you had valuable experiences with. Empirically, we know that those with a college degree have access to better jobs and incomes. That’s a win for you. Pay attention to it.\nAnother long-term approach to changing your mindset is investigating your ideas, thoughts, and feelings about money.\nThe first step is to think about what I call your ”rich life.” When you’re thinking about your finances, ask yourself why do you want to be rich? What does money mean to you and what are you working towards?\nYou’re not just applying an arbitrary monetary value to buying a fancy car or luxury handbag (although those are perfectly fine) but looking deeper to understand what you want your life to look like.\nWe all have a rich life, and everyone’s definition is different. Money is one part of your rich life but what else does it include? Get as specific about your rich life as possible. If you want to travel, what would the destination be? Do you know the exact date and year you would want to travel to this place? If you want a better job, what does that better job look like? Can you visualize the role, the company culture, your pay package, and what kind of projects you’d want to work on?\nYou can also go even more granular and ask yourself what you’d want today to look like.\nThis exercise is all about understanding who you are and what you want your life to look like as precisely as possible. Don’t be afraid to change this vision. It’s likely that some of your values and priorities will shift over time. Let your rich life help you become aware of what you want your life to look like every day — and use it to stay grounded.",
  },
  {
    link: "https://www.inverse.com/mind-body/how-to-achieve-financial-success-the-healthy-way",
    imgSrc:
      "https://imgix.bustle.com/uploads/image/2020/7/28/934b2dcc-6d73-49bd-8f53-98cb38309c73-gettyimages-912018754.jpg?w=1200&amp;h=630&amp;fit=crop&amp;crop=faces&amp;fm=jpg",
    title: "Financial goals can make you feel good — if you follow 3 key rules",
    text: "A psychologist explains how to maintain heath and well-being while pursuing financial goals.",
    categories: [
      "health",
      "wellness",
      "mindfulness",
      "habits",
      "success",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "time management",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.vox.com/even-better/23591325/money-debt-emotions-financial-therapist",
    imgSrc:
      "https://cdn.vox-cdn.com/thumbor/dPucASivDUqeKv-GYFYC4igJXuA=/0x0:8333x4363/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/24420862/GettyImages_1368395193.jpg",
    title: "You’re not bad with money. But you can get better.",
    text: "A financial therapist explains how to shift your personal money narratives.",
    categories: [
      "debt",
      "emotions",
      "mental health",
      "therapy",
      "counseling",
      "psychology",
      "behavioral economics",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "anxiety",
      "stress",
      "trauma",
      "mindfulness",
      "self-care",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.cnbc.com/2021/06/28/here-are-5-ways-to-spend-money-that-can-actually-make-you-happier.html",
    imgSrc:
      "https://image.cnbcfm.com/api/v1/image/106902767-1624632987835-gettyimages-599774043-19c2e5b2-45e4-4731-8b30-27bf66fa2a3b.jpeg?v=1624633088&amp;w=1920&amp;h=1080",
    title: "Here are 5 ways to spend money that can actually make you happier",
    text: "You may be ready to spend more money, but will it bring you joy? Researcher Elizabeth Dunn details five happy spending strategies.",
    categories: [
      "happiness",
      "spending",
      "psychology",
      "well-being",
      "self-improvement",
      "budgeting",
      "saving",
      "investing",
      "philanthropy",
      "health",
      "wellness",
      "education",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.thebalancemoney.com/how-to-set-savings-and-financial-goals-5095454",
    imgSrc:
      "https://www.thebalancemoney.com/thmb/UDMheQsBRK5co3JGFlnVcCzQXes=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/financialgoals-5d957ddaa67e4f578ca531c035ec647f.jpg",
    title: "How To Set Savings and Financial Goals",
    text: "Wanting a comfortable retirement or hoping to have enough money for emergencies isn’t enough. Learn to set specific savings goals to guide financial planning.",
    categories: [
      "savings",
      "goals",
      "planning",
      "budgeting",
      "investing",
      "retirement",
      "wealth",
      "self-improvement",
      "emergency fund",
      "debt repayment",
      "education savings",
      "home buying",
      "car buying",
      "travel savings",
      "risk management",
      "asset allocation",
      "tax planning",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.bogleheads.org/wiki/Emergency_fund",
    imgSrc: "https://www.bogleheads.org/w/images/BogleheadsSiteLogo.svg",
    title: "Emergency fund",
    text: "An emergency fund is a cash reserve required to meet unanticipated needs for cash, such as medical bills, car or home repair, or job loss. The quantity of emergency funds is usually specified as an integer multiple of monthly expenses, e.g., three months to one year's worth of expenses.",
    categories: [
      "emergency fund",
      "savings",
      "risk management",
      "investing",
      "wealth",
      "budgeting",
      "cash reserves",
      "financial planning",
      "debt management",
      "job loss",
      "retirement planning",
      "wealth preservation",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.getrichslowly.org/power-of-compounding",
    imgSrc:
      "https://www.getrichslowly.org/wp-content/uploads/power-of-compounding.jpg",
    title: "The power of compounding: How your wealth snowball grows with time",
    text: "Does compounding matter to your investment returns? HELL YES! Your contributions matter most but it's the power of compounding that leads to a wealth snowball. Want proof? Just look at these numbers...",
    categories: [
      "investing",
      "compound interest",
      "wealth",
      "retirement",
      "savings",
      "growth",
      "self-improvement",
      "stocks",
      "bonds",
      "mutual funds",
      "index funds",
      "asset allocation",
      "portfolio diversification",
      "tax planning",
      "financial planning",
      "risk management",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.thebalancemoney.com/getting-into-money-saving-habit-4125552",
    imgSrc:
      "https://www.thebalancemoney.com/thmb/REUTDwIFstIzWgeEiDVQwx56udI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-875247398-5bf05be246e0fb0051285d80.jpg",
    title: "How to Get Into the Habit of Saving More Money",
    text: "Focus on small wins, make automatic deposits, and resist the temptation to splurge. Soon you'll be on your way to meeting your savings goals.",
    categories: ["money management", "saving", "financial habits", "budgeting"],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://n26.com/en-eu/blog/emergency-fund-and-rainy-day-fund",
    imgSrc:
      "https://images.ctfassets.net/q33z48p65a6w/5jsPg1d5SB5tBgrOueKoJr/8b2e8af70e2cec12377fa06b8c688a3a/rainy_day_fund.jpg?fit=thumb&fm=webp&h=1075&q=70&w=1920",
    title: "What is an emergency and rainy day fund? Here’s how to set one up",
    text: "Life is full of unexpected surprises, but saving for an emergency fund and a rainy day fund can give you some peace of mind. Here’s how.",
    categories: [
      "emergency fund",
      "rainy day fund",
      "saving",
      "financial planning",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.clevergirlfinance.com/blog/saving-money-in-a-jar",
    imgSrc:
      "https://www.clevergirlfinance.com/wp-content/uploads/2022/11/Saving-money-in-a-jar.jpg",
    title: "6 Ideas For Saving Money In A Jar",
    text: "Saving money in a jar is an easy way to save your cash! Check out these great ideas on how to save with a jar plus the best jars to use!",
    categories: ["saving", "budgeting", "money management"],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.sofi.com/learn/content/how-to-start-an-emergency-fund",
    imgSrc:
      "https://d32ijn7u0aqfv4.cloudfront.net/wp/wp-content/uploads/raw/firstaidkit-emergency_SOAD19054_959268466_is_780x440.jpg",
    title: "Starting (and Keeping) an Emergency Fund",
    text: "Saving money for an emergency fund seems daunting, but it is a financial planning tool that can keep you from drowning in unexpected expenses. Emergency savings can help you stay out of debt by providing you with a financial safety net.",
    categories: ["emergency fund", "financial planning", "saving", "budgeting"],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.investopedia.com/investing-in-cryptocurrency-5215269",
    imgSrc:
      "https://www.investopedia.com/thmb/XCqCCcYl4gDg3T79pqvG448Jhis=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Primary_Images-421ad583334747108aab43b54152822f.jpg",
    title: "How to Invest in Cryptocurrency",
    text: "If you are interested in investing in cryptocurrency, then you need to know how to get started. Learn about the risks and potential upside.",
    categories: [
      "crypto",
      "cryptocurrency",
      "investing",
      "digital money",
      "blockchain",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question: "What is cryptocurrency?",
        correctAnswer: "Digital money secured by blockchain technology",
        incorrectAnswers: [
          "Physical money secured by blockchain technology",
          "A type of stock",
        ],
      },
      {
        question:
          "What are the risks associated with investing in cryptocurrency?",
        correctAnswer: "Volatility and regulatory changes",
        incorrectAnswers: [
          "Guaranteed returns and stability",
          "Tax implications and transaction fees",
        ],
      },
      {
        question: "Who should invest in cryptocurrency?",
        correctAnswer: "Investors willing to assume greater risk",
        incorrectAnswers: [
          "Conservative investors",
          "Investors with a low tolerance for risk",
        ],
      },
      {
        question:
          "Some crypto-focused funds invest in cryptocurrency directly, while others invest in crypto-focused companies or derivative securities.",
        correctAnswer: "crypto-focused companies",
      },
    ],
    testedContent:
      "Are you considering investing in cryptocurrency? Though Bitcoin is likely the best-known digital money, thousands of cryptocurrencies already exist.\nCryptocurrency investing can take many forms, ranging from buying cryptocurrency directly to investing in crypto funds and companies. For direct investing in crypto coins, you can buy cryptocurrency using a crypto exchange or through certain broker-dealers. Find out more about how you can invest in one of the newest and most inventive asset classes available.\nCryptocurrency is digital money that is secured by blockchain technology.\nCryptocurrency investing can take many forms, ranging from buying cryptocurrency directly to investing in crypto funds and companies.\nYou can buy cryptocurrency using a crypto exchange or through certain broker-dealers.\nPay attention to transaction fees when making crypto purchases because these fees can vary widely among currencies.\nInvesting in cryptocurrency is risky, so it's important not to invest more money than you can afford to lose.\nWhen you think of investing in cryptocurrency, you might think about buying and holding one or more crypto coins. Buying cryptocurrency directly is probably the most common way to add crypto exposure to your portfolio, but when it comes to investing in cryptocurrency, you have a few different options:\nBuy cryptocurrency directly: You can choose to directly purchase and store one or more cryptocurrencies. Your options range from the most established digital currencies like Ethereum and Bitcoin to virtually unknown coins that are newly released in an initial coin offering (ICO).\nInvest in cryptocurrency companies: You can invest in companies with a partial or total focus on cryptocurrency. Your options include cryptocurrency mining companies, mining hardware makers, companies like Robinhood Markets Inc. (HOOD) and PayPal Holdings Inc. (PYPL) that support cryptocurrency, and many others with varying levels of crypto exposure. You also can invest in companies like MicroStrategy Inc. (MSTR), which hold large amounts of cryptocurrency on their balance sheets.\nInvest in cryptocurrency-focused funds: If you don't want to choose among individual cryptocurrency companies, then you can decide to invest in a cryptocurrency-focused fund instead. You have a choice of exchange-traded funds (ETFs), such as index funds and futures funds, in addition to a range of cryptocurrency investment trusts.\nSome crypto-focused funds invest in cryptocurrency directly, while others invest in crypto-focused companies or derivative securities such as futures contracts.\nInvest in a cryptocurrency Roth IRA: If you want to invest in cryptocurrency and also garner the tax advantages afforded by an individual retirement account (IRA), then you can consider investing in a cryptocurrency Roth IRA. Using the services of a crypto IRA provider can also facilitate more secure storage for your cryptocurrency holdings.\nBecome a crypto miner or validator: Perhaps the most direct way to invest in cryptocurrency is to mine it or act as a validator in a crypto network. Cryptocurrency miners and validators earn rewards in crypto, which they can either hold as investments or exchange for another currency.\nIf you want to invest in cryptocurrency directly, then you can use a cryptocurrency exchange. Here's how to buy cryptocurrency through an exchange:\n1. Choose which cryptocurrency exchange you want to use. Your best bet is a reputable, well-known exchange with a large selection of currencies.\n2. Establish an account with the cryptocurrency exchange. You will need to provide your personal information and verify your identity to complete the registration process.\n3. Fund your account with fiat money. Before you can buy any crypto, you need to fund your exchange account with another currency, such as U.S. dollars.\n4. Decide which cryptocurrency you want to buy. You can choose to invest in one or many cryptocurrencies. Research your options to help you decide.\n5. Place a buy order for your chosen cryptocurrency. Follow the steps required by the exchange to submit and complete a buy order for one or more cryptocurrencies.\n6. Store your cryptocurrency in a digital wallet. After your purchase is complete, the information you need to access your cryptocurrency is held in a digital wallet. That crypto wallet can be hosted either by the cryptocurrency exchange or an independent wallet provider.\nAs an investor in cryptocurrency, you need to decide how much of your portfolio to allocate to digital assets.\nA best practice among investors is to periodically review your entire portfolio to assess the need to rebalance your holdings. That might mean increasing or scaling back your crypto exposure, depending on your investment goals and other financial needs.\nInvesting in cryptocurrency is considered risky. The prices of cryptocurrencies, even the most established ones, are much more volatile than the prices of other assets like stocks. The prices of cryptocurrencies in the future could also be affected by regulatory changes, with the worst-case possibility that cryptocurrency becomes illegal and therefore worthless.\nMany investors are nonetheless attracted to the potential upside of investing in crypto. If you decide to invest, it's important to carefully research any digital coin before buying it. Pay attention to transaction fees when making crypto purchases because these fees can vary widely among currencies.\nThe cryptocurrency space is evolving rapidly, so it's also important to pay attention to new developments that may affect your crypto holdings. Cryptocurrency investors need to understand the tax consequences of using crypto, especially if they purchase something or sell their crypto investments.\nGiven the riskiness of cryptocurrency as an asset class, it's especially important not to invest more money in crypto than you can afford to lose.\nInvesting in cryptocurrency is not for everyone. The prices of cryptocurrencies can be volatile, which makes this type of investing likely a poor choice for conservative investors. If you are willing to assume greater risk as an investor, then investing in one or more cryptocurrencies may be right for you.\nYou can invest in Bitcoin directly by using one of the major cryptocurrency exchanges, such as Coinbase or Binance. Another way to gain investment exposure to Bitcoin is to buy shares in a company with significant Bitcoin exposure, such as a Bitcoin mining company. A third option is to invest in a Bitcoin-focused fund such as an exchange-traded fund (ETF).\nYou can invest in Bitcoin or another cryptocurrency without spending much money. Using the Coinbase platform, for example, you can buy cryptocurrency with as little as two units of your local currency.\nFinding the right financial advisor that fits your needs doesn’t have to be hard. SmartAsset’s free tool matches you with fiduciary financial advisors in your area in 5 minutes. Each advisor has been vetted by SmartAsset and is legally bound to act in your best interests. If you’re ready to be matched with local advisors that will help you achieve your financial goals, get started now.",
  },
  {
    link: "https://www.thetimes.co.uk/money-mentor/article/cryptocurrency-good-investment",
    imgSrc:
      "https://www.thetimes.co.uk/money-mentor/wp-content/uploads/2021/04/GettyImages-1314512617.jpg?resize=600,375",
    title: "Is cryptocurrency a good investment?",
    text: "Cryptocurrency may be a good investment if you are willing to accept it is a high risk gamble which could pay off – but also that there is a strong chance you could lose all of your money.",
    categories: ["cryptocurrency", "investment", "risk management"],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://solberginvest.com/blog/the-ultimate-strategy-for-investing-in-shitcoins",
    imgSrc:
      "https://solberginvest.com/wp-content/uploads/2021/06/sincerely-media-XJnjN1eRSEk-unsplash-e1622813446672.jpg",
    title: "The Ultimate Strategy For Investing In Shitcoins",
    text: "Investing in shitcoins is really exciting. It can be insanely profitable, as these coins can go 10x in a matter of a few hours. That being said, it’s also one of the fastest ways to go broke if you mess up. What you need to do is to formulate a strategy before investing in shitcoins",
    categories: [],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.coinbase.com/learn/crypto-basics/what-is-a-blockchain",
    imgSrc:
      "https://images.ctfassets.net/q5ulk4bp65r7/70c1NBb3A7nvNpx38gSvtd/725e6c5da4960a5a17657c02b80dd596/Learn_Illustration_Ultimate_Guide_Blockchain.png?w=768&fm=png",
    title: "What is a blockchain?",
    text: "Cryptocurrencies like Bitcoin and Ethereum are powered by a technology called the blockchain.",
    categories: [
      "crypto",
      "cryptocurrency",
      "blockchain",
      "bitcoin",
      "ethereum",
      "digital assets",
      "decentralized technology",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://hackernoon.com/wtf-is-the-blockchain-1da89ba19348",
    imgSrc:
      "https://hackernoon.imgix.net/hn-images/1*dcRQxEbvbfPa1ESsylcDng.png",
    title: "WTF is The Blockchain?",
    text: "Unless you’re hiding under the rock, I am sure you’d have heard of Bitcoins and Blockchain. After all, they are the trending and media’s favorite topics these days — the buzzwords of the year. Even the people who’ve never mined a cryptocurrency or understand how it works, are talking about it. I have more non-technical friends than technical ones. They have been bugging me for weeks to explain this new buzzword to them. I guess there are thousands out there who feel the same. And when that happens, there comes a time to write something to which everyone can point the other lost souls to — that’s the purpose of this post — written in plain english that any regular internet user understands.",
    categories: [
      "blockchain",
      "cryptocurrency",
      "crypto",
      "distributed ledger technology",
      "decentralisation",
      "bitcoin",
      "ethereum",
      "smart contracts",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://hackernoon.com/making-sense-of-cryptoeconomics-5edea77e4e8d",
    imgSrc:
      "https://hackernoon.imgix.net/hn-images/1*_ywvkl6JQHRn2d00MRv4_A.png",
    title: "Making Sense of 'Cryptoeconomics'",
    text: "The term “cryptoeconomics” causes a lot of confusion. People are often unclear on what it is supposed to mean. The word itself can be misleading, as it suggests that there is a parallel “crypto” version of the whole of economics. This is wrong, and Parker is right to mock such a generalization. In simple terms, cryptoeconomics is the use of incentives and cryptography to design new kinds of systems, applications, and networks.",
    categories: [
      "cryptoeconomics",
      "crypto",
      "cryptocurrency",
      "blockchain",
      "smart contracts",
      "game theory",
      "mechanism design",
      "token economics",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.kraken.com/learn/what-is-blockchain-technology",
    imgSrc:
      "https://assets-cms.kraken.com/images/51n36hrp/facade/b4b7d7de97cd77488c1dc7654919b6cf2e6695b9-1638x837.png?w=2880&amp;fit=min",
    title: "What is Blockchain Technology?",
    text: "What is a blockchain technology? Learn how one of the central building blocks that powers crypto assets works with Kraken – the world’s most secure crypto exchange.",
    categories: [
      "blockchain",
      "cryptocurrency",
      "bitcoin",
      "ethereum",
      "decentralisation",
      "distributed ledger technology",
      "digital assets",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.worth.com/how-cryptocurrency-could-inspire-a-new-kind-of-financial-literacy",
    imgSrc:
      "https://www.worth.com/wp-content/uploads/2021/03/andre-francois-mckenzie-9qpCNwDeBVU-unsplash-scaled-e1617133903685.jpg",
    title: "How Cryptocurrency Could Inspire a New Kind of Financial Literacy",
    text: "As we embark on a new era of money, we’re in a unique moment. Cryptocurrency trading has attracted the interest of a whole new swath of the population. If we use this moment well, we have the opportunity to design a new financial literacy.",
    categories: [
      "cryptocurrency",
      "crypto",
      "financial literacy",
      "investing",
      "blockchain",
      "wealth management",
      "economics",
      "financial planning",
    ],
    length: 0,
    points: 0,
    questionItems: [],
  },
  {
    link: "https://www.bogleheads.org/wiki/Prioritizing_investments",
    imgSrc: "https://www.bogleheads.org/w/images/BogleheadsSiteLogo.svg",
    title: "Prioritizing investments",
    text: "Investors are faced with a variety of choices on where to invest their money (e.g., a taxable account, a 401(k), or an IRA). Knowing which accounts to invest in first will maximize return with a minimum of taxes. Prioritizing investments guides investors on the appropriate order of placing their investments into these accounts.",
    categories: [
      "investing",
      "retirement planning",
      "tax planning",
      "emergency fund",
      "debt payoff",
      "asset allocation",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question:
          "What is the first step in funding an investment account according to the article?",
        correctAnswer: "Establish an emergency fund",
        incorrectAnswers: [
          "Contribute to an employer retirement plan",
          "Contribute to a Health Savings Account",
          "Invest inside a taxable account",
        ],
      },
      {
        question:
          "What is the second step in funding an investment account according to the article?",
        correctAnswer: "Contribute to an employer retirement plan",
        incorrectAnswers: [
          "Contribute to a Health Savings Account",
          "Establish an emergency fund",
          "Pay off high-interest debt",
        ],
      },
      {
        question:
          "What should an investor do if their employer offers a match for their retirement plan contributions?",
        correctAnswer: "Contribute only enough to receive the employer match",
        incorrectAnswers: [
          "Contribute up to the annual contribution limit",
          "Do not contribute to the retirement plan",
          "Contribute to a Health Savings Account",
        ],
      },
      {
        question:
          "After receiving a full employer match in a retirement plan, an should investor prioritize paying off high-interest debt.",
        correctAnswer: "high-interest debt",
      },
    ],
    testedContent:
      "Investors are faced with a variety of choices on where to invest their money (e.g., a taxable account, a 401(k), or an IRA). Knowing which accounts to invest in first will maximize return with a minimum of taxes. Prioritizing investments guides investors on the appropriate order of placing their investments into these accounts.\nInvestors should take care that any investment priority decision is aligned with their Investment Policy Statement.\nHere is a general account funding priority that often works well for many people (not all points will apply to everyone).\n1. Establish an emergency fund to your satisfaction. If you have many other high financial priorities (like paying off high-interest debt), start with a smaller emergency fund, and grow it later over time, as those other priorities are satisfied.\n2. Contribute to an employer retirement plan (e.g. 401(k) or 403b) enough to get the full employer match (the match is like free money, your best possible investment).\n3. Pay off high-interest debt (a guaranteed high return, the next best thing to free money).\n4. Contribute to a Health Savings Account (HSA) if a high deductible health plan is appropriate for your needs (you can think of HSA contributions as also getting a match, from the IRS).\n5. Contribute the maximum to an IRA, traditional or Roth (or backdoor Roth technique), depending on eligibility and personal circumstances. (See below for situations where you may prefer to swap steps 5 and 6.)\n6. Contribute the remainder of the maximum employee contribution to the work-based plan.\n7. If your plan supports it, employ the mega-backdoor Roth strategy.\n8. Pay off medium-interest debt (eg. student loans, car loans, personal loans), especially if the interest is not tax-deductible.\n9. Invest inside a taxable account.\n10. Pay off low-interest debt (eg. most mortgages, some car loans).\nIt is important to realize that these steps are not cast in stone. The above list should be considered with some flexibility for an investor's needs and personal preferences.\nIf the company plan offers good, low-cost funds, it may be preferable to contribute to the company plan before contributing to an IRA; see: Comparison between IRAs and employer plans.\nAlso, an investor's marginal tax rate may influence the decision: those subject to higher marginal tax rates should consider higher contributions to a tax-deferred plan (e.g. traditional 401(k) or IRA) rather than a post-tax plan (e.g. Roth 401(k) or IRA); see Traditional versus Roth for more guidance.\nIf you prefer traditional to Roth, and traditional contributions to the employer's plan are needed to reduce your Modified Adjusted Gross Income (MAGI) for traditional IRA purposes enough to allow a full or partial IRA deduction (see IRA Deduction Limits), consider swapping steps 5 and 6.\nTable 1 describes the rationale for investing in the order previously described.\n1. Start building an emergency fund: Have enough cash on hand to cover unplanned expenses. While the exact amount depends on your risk tolerance, a common rule of thumb is to start with one month of expenses, and as you satisfy other financial priorities, grow it over time to around 3-12 months of expenses. (See: Emergency fund.)\n2. Contribute to a work-based retirement plan (eg. 401(k) or 403(b)) enough to get the full employer match: Not getting an employer match is like letting your employer keep part of your salary.\n3. Pay off high-interest debt: Typically these include credit cards and other unsecured loans. Paying off a high-interest debt is a guaranteed high return on your investment, the next best thing to free money.\n4. Contribute to a Health Savings Account (HSA) if a high deductible health plan is right for your needs: HSAs offer tax-free contributions, growth, and withdrawals when used for qualified medical expenses. You can view HSA contributions as being matched by the IRS. If you are in a 25% tax bracket, it costs you $750 to put $1000 in your HSA, and once it is there, it won't be taxed at all as long as you spend it for medical care, so this is as good as $1000 in a Roth IRA.\nAfter age 65, the HSA can also be used for non-medical expenses, with such withdrawals taxed at your regular tax rate. So if you are unlucky and are too healthy after 65, the HSA is still as good as a pre-tax retirement account. Unlike pre-tax retirement accounts, HSA contributions made through an employer are also payroll tax-deductible.\nUse of an HSA requires participation in an IRS qualified high deductible health plan (HDHP) at work. Look at your particular health care needs to decide if you may be better off with a traditional health care plan or an HDHP plus HSA. If the latter, then using the HSA as an investment account can be advantageous.\n5.-7. Contribute to available retirement accounts (eg. IRA, 401(k), 403(b), 457(b)) without a match: Retirement accounts offer either an immediate tax deduction and tax-deferred growth (traditional) or life-long tax-free growth (Roth), plus asset protection and estate planning benefits. These accounts have annual contribution limits which are lost if not used.\nInvestors may have to choose among IRA vs. employer plan and/or traditional vs. Roth accounts and should consult those articles for more details.\nDeductible IRA contributions are subject to income limits, but the income limit for contributing to a Roth IRA may be circumvented by the Backdoor Roth process. Employer plans may also offer mega-backdoor Roth contributions, but these should be made only after normal contributions.\n8. Pay off medium-interest debt: Typically these include student loans, car loans, personal loans, and Home Equity Lines of Credit (HELOCs). The choice to pay off debt or invest is based mostly on the expected after-tax rate of return. When the returns are similar, secondary factors sway the decision; see: Paying down loans versus investing.\n9. Invest in a taxable account: As you consider all these steps, keep in mind that your asset allocation (ratio of stocks to bonds), which sets your portfolio's level of acceptable risk, is the single most influential decision you can make on your portfolio's performance. Your chosen asset allocation (% stocks / % bonds) may direct you to skip some of these steps.\n10. Pay off low-interest debt: Typically these include mortgages and other secured debt. Paying off low-interest debt on good terms should be a lower priority than most other funding options, but a higher priority than investing in low-return investments with no tax advantages.\nMany company plans contain high-cost funds which make them unattractive. If you have such a plan, look for one or two index funds or a bond fund that can be used. If your company offers matching funds up to a certain contribution level, it's always wise to use the company plan. If there is no match, the power of tax-deferred compounding and automatic contributions still favors using the plan with limited contributions.\nAlso, if you leave your current employer you will most likely be able to rollover the assets in your poor-quality company plan to either a better company plan, or to an IRA.",
  },
  {
    link: "https://www.bogleheads.org/wiki/Systematic_investing",
    imgSrc: "https://www.bogleheads.org/w/images/BogleheadsSiteLogo.svg",
    title: "Systematic investing",
    text: "Systematic investing occurs when investors make regular, equal payments into a mutual fund, trading account or retirement account, such as a 401k. Systematic investing encourages the establishment of a regular savings habit, and, because purchases are made at various market prices, investors, in essence, dollar-cost-average the average purchase price of the investment.",
    categories: [
      "Investing",
      "Systematic Investing",
      "Mutual Funds",
      "Trading Account",
      "Retirement Account",
      "Dollar-Cost Averaging",
      "Automatic Investment Plan",
      "Contractual Investment Plan",
      "Periodic Investment Plan",
      "FINRA",
      "Investment Programs",
      "Low-Cost Mutual Funds",
      "Low-Cost Variable Annuities",
      "529 Savings Plan",
      "Employer Savings Plans",
      "Payroll Deduction",
      "Securities Laws",
    ],
    length: 0,
    points: 0,
    questionItems: [
      {
        question:
          "Systematic investing encourages the establishment of a regular savings habit.",
        correctAnswer: "regular",
      },
      {
        question: "What is dollar-cost averaging?",
        correctAnswer:
          "Making regular, equal payments into a mutual fund or retirement account.",
        incorrectAnswers: [
          "The practice of investing in high-risk assets",
          "Investing in low-cost stocks",
          "Investing only in mutual funds",
        ],
      },
      {
        question: "What is a major characteristic of contractual plans?",
        correctAnswer: "High first-year cost.",
        incorrectAnswers: [
          "Low first-year cost",
          "Direct mutual fund ownership",
          "Low commission costs",
        ],
      },
      {
        question:
          "A typical SIP contractual plan allows an investor to accumulate shares of a mutual fund indirectly by making small regular monthly payments over a period of 10, 15 or 25 years.",
        correctAnswer: "25",
      },
    ],
    testedContent:
      "Systematic investing occurs when investors make regular, equal payments into a mutual fund, trading account or retirement account, such as a 401k. Systematic investing encourages the establishment of a regular savings habit, and, because purchases are made at various market prices, investors, in essence, dollar-cost-average the average purchase price of the investment.\nWhile most investors experience systematic investment by participating in employer-provided contributory retirement plans, investment firms supply a number of programs which allow investors to set up an individual systematic investment program. These programs include Automatic investment plans and Contractual investment plans.\nMany investment institutions offer an Automatic Investment Plan (AIP), an investment program that allows investors to contribute small amounts of money in regular (monthly, quarterly, semiannual, or annual) intervals. Funds are automatically deducted from the investor's checking/savings account or paycheck. Mutual funds (both in taxable accounts and IRA accounts), variable annuity subaccounts, and 529 savings plan funds are some of the most common vehicles offering an AIP option.\nInvestors wishing to establish an AIP employing the principles embedded in the Bogleheads' philosophy might consider establishing AIP programs with low cost no-load mutual funds, no-load low cost variable annuities, and direct sold low-cost 529 plan portfolios.\nFINRA, in an investor alert regarding contractual plans, offers the following advice: 'For a specific type of systematic investment plan—sometimes referred to as a 'contractual plan' or 'periodic payment plan'—an investor must make a long-term commitment of 10 or 15 years. While the majority of these plans are sold to military personnel, they are also sold to civilians. These plans come with high upfront costs and are expensive if the full term of payment is not completed. If your goal is to save for retirement, most employer savings and retirement plans allow you to save through payroll deduction. Military personnel can make long-term periodic investments in the U.S. Thrift Savings Plan. This plan has no up-front load and low on-going expenses'\nIn the U.S. Systematic Investment Plans (SIP) are regulated as Periodic Investment Plans under the federal securities laws. A typical SIP contractual plan allows an investor to accumulate shares of a mutual fund indirectly by making small regular monthly payments, usually as little as $50, over a period of 10, 15 or 25 years. Historically, the majority of contractual plans have been sold to military personnel. These plans impose high upfront commission costs, as much as 50% of the first year payments, and are especially expensive if the full term of the plan is not completed.\nContractual plans have the following characteristics:\nHigh first-year cost. You are required to pay a creation and sales charge equal to as much as 50 percent of the first 12 monthly investments. If you increase the amount of your monthly payments, you may owe an additional creation and sales charge on the new investment.\nLong-term investment. Typically, systematic investment plans require 180 fixed monthly payments over a 15-year period, with the option of making payments for up to 25 years (300 investments).\nNo direct mutual fund ownership. Investments in a contractual plan are placed in a trust. The trust invests your regular payments, minus fees and expenses, in shares of a mutual fund.\nMissed Payments. The sponsor may terminate your plan if you fail to make investments for a period of 6 or 12 consecutive months.\nFees and expenses. Plan expenses include creation and sales charge fees, mutual fund management and distribution expenses, and various custodial and service fees. The cost burden of the creation and sales charge is revealed in the following table:\nCancellation and Refund Rights. An investor in contractual plan can cancel the contract with the following rights.\n45-Day Cancellation Right. You will receive a notice of your cancellation rights within 60 days after your first investment in the plan. You can cancel your plan within 45 days of the mailing date of that notice. If you choose to cancel your plan, you will receive a cash refund equal to (1) the current value of your investment and (2) the total sales and creation charge you paid. The current value of your shares may be more or less than your original investment\n18-Month Cancellation Right. You are also able cancel the plan within 18 months after your first investment in the plan. If you choose to cancel your plan after the 45-day cancellation period, you will receive a cash refund equal to (1) the current value of your investment and (2) the amount of the sales and creation charge you paid that exceeds 15 percent of the total investments you've made in the plan. You should receive a notice of your 18-month cancellation right if you miss (1) three or more of your monthly investment payments during the first 15 months of the plan or (2) one or more payments after the first 15 months.\nIf you cancel your plan after 18 months, you will not be entitled to a refund of any creation and sales charge. This charge can be up to 50 percent of your periodic investments.",
  },
];
